name: ci

on:
  push:
    branches:
      - main
      - feature/build-two-images

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      image: ghcr.io/${{ github.actor }}/runner-krunvm-base
      file: Dockerfile.base
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
