name: ci

on:
  push:
    branches:
      - main

jobs:
  build-base:
    uses: ./.github/workflows/_build.yml
    with:
      image: ${{ github.actor }}/runner-krunvm-base
      file: Dockerfile.base
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  build-main:
    needs:
      - build-base
    uses: ./.github/workflows/_build.yml
    with:
      image: ${{ github.actor }}/runner-krunvm
      file: Dockerfile
      build-args: |
        VERSION=${{ needs.build-base.outputs.version }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
