name: ci

on:
  push:
    branches:
      - feature/*

jobs:
  test:
    runs-on: fedora
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: blob:none
      - name: Test Environment
        run: |
          env
